server:
  port: 8082

spring:
  application:
    name: "Loan-Service"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/sakila
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    